apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otelcol-contrib.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "otelcol-contrib.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  collector-config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
